(define (problem grid-2rows-2cols-1shapes-3keys-3locks)
    (:domain grid)
    (:objects
    pos0_0 pos0_1 pos1_0 pos1_1
    shape0
    key0 key1 key2
    )
    (:init
       (arm_empty)
       (place pos0_0)
       (place pos0_1)
       (place pos1_0)
       (place pos1_1)
       (open pos0_0)
       (at_robot pos0_0)
       (objshape shape0)
       (key key0)
       (key key1)
       (key key2)
       (below pos1_0 pos0_0)
       (below pos1_1 pos0_1)
       (left pos0_1 pos0_0)
       (left pos1_1 pos1_0)
       (locked pos0_1)
       (locked pos1_1)
       (locked pos1_0)
       (lock_shape  pos0_1 shape0)
       (lock_shape  pos1_1 shape0)
       (lock_shape  pos1_0 shape0)
       (key_shape  key0 shape0)
       (key_shape  key1 shape0)
       (key_shape  key2 shape0)
       (at key0 pos1_0)
       (at key1 pos0_0)
       (at key2 pos0_1)
    )
    (:goal (and
       (at key0 pos1_1)
       (at key1 pos0_1)
       (at key2 pos1_1)
    )))
