(define (problem strips-gripper-x-1)
   (:domain gripper)
   (:objects rr lr leftgrip rightgrip ball1)
   (:init (room rr)
          (room lr)
          (left lr rr)
          (neq rr lr)
          (neq lr rr)
          (ball ball1)
          (at_robby lr)
          (free leftgrip)
          (free rightgrip)
          (at ball1 lr)
          (gripper leftgrip)
          (gripper rightgrip))
   (:goal (and 
               (at ball1 rr))))
