(define (problem strips-gripper-x-2)
   (:domain gripper)
   (:objects lr rr ball2 ball1 leftgrip rightgrip)
   (:init (room lr)
          (room rr)
          (left lr rr)
          (lroom lr)
          (rroom rr)
          (neq rr lr)
          (neq lr rr)
          (ball ball2)
          (ball ball1)
          (at_robby lr)
          (free leftgrip)
          (free rightgrip)
          (at ball2 lr)
          (at ball1 lr)
          (gripper leftgrip)
          (gripper rightgrip))
   (:goal (and 
               (at ball2 rr)
               (at ball1 rr))))