(define (problem strips-gripper-x-1)
   (:domain gripper-slots)
   (:objects rr lr ball1 leftgrip rightgrip slotl1 slotl2 slotl3 slotl4 slotr1 slotr2 slotr3 slotr4)
   (:init (room rr)
          (room lr)
          (left lr rr)
          (neq rr lr)
          (neq lr rr)
          (ball ball1)
          (at_robby lr)
          (free leftgrip)
          (free rightgrip)
          (at ball1 lr)
          (gripper leftgrip)
          (gripper rightgrip)
          (at_robby_slot lr slotl1)
          (at_slot ball1 lr slotl2)
          (free_slot lr slotl3)
          (free_slot lr slotl4)
          (free_slot rr slotr1)
          (free_slot rr slotr2)
          (free_slot rr slotr3)
          (free_slot rr slotr4)
          (slotof slotl1 lr) (slotof slotl2 lr) (slotof slotl3 lr) (slotof slotl4 lr)
          (slotof slotr1 rr) (slotof slotr2 rr) (slotof slotr3 rr) (slotof slotr4 rr)
          (left slotl1 slotl2) (left slotl3 slotl4) (left slotr1 slotr2) (left slotr3 slotr4)
          (below slotl3 slotl1) (below slotl4 slotl2) (below slotr3 slotr1) (below slotr4 slotr2)
          )
   (:goal (and 
               (at ball1 rr))))