(define (problem strips-gripper-x-3)
   (:domain gripper-slots)
   (:objects lr rr ball3 ball2 ball1 leftgrip rightgrip slotl1 slotl2 slotl3 slotl4 slotr1 slotr2 slotr3 slotr4)
   (:init (room lr)
          (room rr)
          (left lr rr)
          (neq rr lr)
          (neq lr rr)
          (ball ball2)
          (ball ball1)
          (ball ball3)
          (at_robby lr)
          (free leftgrip)
          (free rightgrip)
          (at ball2 lr)
          (at ball1 lr)
          (at ball3 lr)
          (gripper leftgrip)
          (gripper rightgrip)
          (at_robby_slot lr slotl1)
          (at_slot ball1 lr slotl2)
          (at_slot ball2 lr slotl3)
          (at_slot ball3 lr slotl4)
          (free_slot rr slotr1)
          (free_slot rr slotr2)
          (free_slot rr slotr3)
          (free_slot rr slotr4)
          (slotof slotl1 lr) (slotof slotl2 lr) (slotof slotl3 lr) (slotof slotl4 lr)
          (slotof slotr1 rr) (slotof slotr2 rr) (slotof slotr3 rr) (slotof slotr4 rr)
          (left slotl1 slotl2) (left slotl3 slotl4) (left slotr1 slotr2) (left slotr3 slotr4)
          (below slotl3 slotl1) (below slotl4 slotl2) (below slotr3 slotr1) (below slotr4 slotr2)
          )
   (:goal (and (at ball3 rr)
               (at ball2 rr)
               (at ball1 rr))))