(define (problem 3cell1locked1key1openableleft)
  (:domain grid)
  (:objects node1 node2 node3 key0 triangle)
  (:init
     (place node1) (place node2) (place node3)
	 (arm_empty) (objshape triangle)
	 (left node1 node2) (right node2 node1)
	 (left node2 node3) (right node3 node2)
	 (open node1) (open node2)
	 (locked node3) (lock_shape node3 triangle)
	 (key key0)
	 (key_shape key0 triangle) (at key0 node1)
	 (at_robot node1))
  (:goal (at_robot node1))
  )
